# 各個体がどのような(TE,Deg)の値を持つか可視化

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import pickle
import sys
sys.path.append('../GA')
from modules import Deg_predictor
from modules import TE_predictor

# job728 selNSGA3 cxUniform 50個
# job743 10個
# job744 5個
# job745 11個
# job782 10個
nsga3_unif = {
# 'job728' : ['GCCTCGCGCCCCCGCGAAGCCGACGGCGACGGGCACCACGCGGATACAAC', 'CTACACGCTTTATAGGCAAAGGACACCCATATTTTCTCTGGGGCCTTTCA', 'GCCTCGCGCCCCGGCGAAGCCGACGGCCACCGGCACCACGCGGATACAAC', 'CTACACGCTTTCTCGACAAAAGACACCCATATTTTCTCTGGGGCCTTTCA', 'CTACACGCTTTATAGGCAAAGGCCACCCATATTTACTCTGGGGCCTTTCA', 'GCCGGCCGCTCGCCCCCAGCCGCCCCGCGTGCCCCACGCGCACCATCAAC', 'GCCTGCCGCCCGGCCCCAGCCGCCCCCCGTGCCCCACGCGCACCATCAAC', 'GCCGGCCGCTCGCCCCCAGCCGCCCCGCGTCCCCGACGCGCACCATCAAC', 'GCGCCGCGCACCGCGCCCCGCAGCGCCACCAGCCGCGCCGCGCCAACAAC', 'GCCTGCCGCCCGGCCCCAGCCGACCCGCGTGCCCCACGCGCACCATCAAC', 'GCCGGCCGCTCGGCCCCAGCCGCCCCGCGTGCCCCACGCGCACCAACAAC', 'CTACACGCTTTCTTGACAAAAGACACCCATATTTTCTCTGGGGCCTTTCA', 'CTACACGCTTTTTGGACCAAAGACACCCATATTTTCTCTGGGGCCTTTCA', 'GCCGGCCGCTCGCCCCCAGCCGCCCCGCGTCCCCGACGCGCTCCAACAAC', 'GCCTCGCGCCCCGGCGGAGCCGACGGCCACCGGCACCACGCGGATACAAC', 'GCCGGCCGCTCGCCCCCCGCAGCCCCGCGTGCCCCACGCGCGCCAACAAC', 'CCCCCGCGCCCCGAGCCCCGCAGCGCCGCCAGCCGCGCCGCGCCAACAAC', 'GCCGGCCGCTCGCCCCCAGCCGCCCCGCGTGCCCCACGCGCTCCAACAAC', 'GCCGGCCGCTCGCCCCCAGCCGCCCCGCGTCCCCCACGCGCACCATCAAC', 'GCCTGCCGCCCGGCCCCAGCCGCCCCGCGTGCCCCACGCGCGCCATCAAC', 'GCCCCGCGCCCCGCGCCCCGCAGCGCCGCCAGCCGCGCCGCGCCAACAAC', 'GCCGGCCGCTCGCCCCCAGCCGCCCCGCGTGCCCCACGCGCGCCATCAAC', 'CTACACGCTTTCTGGACAAAAGACACCCATATTTTCTCTGGGGCCTTTCA', 'GCGCCGCGCACCGCGCCCCGCAGCGCCGCCACCCGCGCCGCGCCAACAAC', 'CTACACGCTTTATAGGCAAAGGCCACCCATATTTACTCTGGGGCCTTTCC', 'GCCGGCCGCTCGCCCGCAGCCGCCCCGCGTCCCCCACGCGCACCATCAAC', 'CCCCCGCGCCCCGCGCCCCGCAGCGCCGCCAGCCGCGCCGCGCCAACAAC', 'GCCGGCCGCTCGCCCGCAGCCGCCCCGCGTCCCCCACGCGCTCCAACAAC', 'GCGCCGCGCACCGCGCCCCGCAGCGCCGCCAGCCGCGCCGCGCCAACAAC', 'GCCTCGCGCCGCCCCGCAGCCGACGGCGCCGCGCACCACGCGGATACAAC', 'GCCTCGCGCCCCCGCGAAGCCGACGGCGCCGCGCACCACGCGGATACAAC', 'GCCTGCCGCCCGGCCCCAGCCGCCCCGCGTGCCCCACGCGCACCATCAAC', 'GCCTCGCACCCCCGCGAAGCCGACGGCGACGGGCACCACGCGGATACAAC', 'GCCTCGCGCCCCCGCGAAGCCGACGGCCACGGGCACCACGCGGATACAAC', 'GCCGGCCGCTCGCCCCCCGCCGCCCCGCGTGCCCCACGCGCGCCAACAAC', 'GCCTCGCGCCCCCGCGAAGCCGCCGGCGCCGCGCACCACGCGGATACAAC', 'GCCTGCCGCCCGGCCCCAGCCGCCCCGCGTCCCCGACGCGCTCCAACAAC', 'GCCTCGCGCCCCGGCGAAGCCGACGGCGCCGCGCACCACGCGGATACAAC', 'GCCGGCCGCTCGCCCCCCGCAGCCCCGCGAGCCCCACGCGCGCCAACAAC', 'CTACACGCTTTTTGGACAAAAGACACCCATATTTTCTCTGGGGCCTTTCA', 'GCCGGCCGCTCGCCCCCCGCAGCCCCGCGTGCCCCACGCGCACCATCAAC', 'GCCGGCCGCTCGCCCCCAGCCGCCCCGCGTCCCCCACGCGCGCCAACAAC', 'GCCGGCCGCTCGCCCCCCGCAGCCCCGCGTGCCCCACGCGCGCCATCAAC', 'GCCTCGCCCGGGCCCGCAGCCGACGGCCCCGCGCACCACGCGGATACAAC', 'GCCGGCCGCTCGCCCCCCGCCGCCCCGCGTGCCCCACGCGCACCAACAAC', 'GCCTGGCGCCCGGCCCCAGCCGACCCGCGTGCCCCACGCGCACCATCAAC', 'GCCGGCCGCTCGCCCCCCGCCGCCCCGCGTGCCCCACGCGCTCCAACAAC', 'CTACACGCTTTTTGGACAAAAGACACCCATATTTACTCTGGGGCCTTTCA', 'GCGCCGCGCACCGCGCCCCGCAGCGCCCCGACCCGCGCCGCGCCAACAAC', 'GCCTCGCGCCCCCGCGAAGCCGACGGCCACGGGCACCACGCGAATACAAC'],
'job743' : ['GCCGGCCGCCTGGCACAGCCCCCAGCCGCACCCGGCCGGCACAACAACGA', 'GCCGGCCGCCTGGCACAGGCCCCAGCCCCACCCGGCCGGCACAACAACGA', 'GCCGGCCGCCTGGCACAGGCCCCAGCCGCACCCGGCCGGCACAACAACGA', 'GCCGGCCGCCCGGCACCGCCCCCAGCCGCACCCGGCCGGCACAACAACGA', 'GCCGGCCGCCTGGCACAGCCCGCAGCCGCACCCGGCCGGCACAACAACGA', 'GCCGGCCGCCTGGCACCGCCCGCAGCCGCACCCGGCCGGCACAACAACGA', 'GCCGGCCGCCCGGCACCGCCCGCAGCCGCACCCGGCCGGCACAACAACGA', 'GCCGGCCGCCTGGCACAGGCCCCAGCCCCACCCGGCCCGCACAAATACGA', 'GCCGGCCGCCCGGCACAGCCCCCAGCCGCACCCGGCCGGCACAACAACGA', 'GCCGGCCGCCTGGCACAGCCCCCAGCCCCACCCGGCCCGCACAACTACGA'],
'job744' : ['GCCGGCCCGCAGGCGCCCCCAGCCACCGGCACCACCGCGCCTACAACGAC', 'GCCGGCCCGCAGGCGCCACCGGCCACCGGCACCCCCGCGCCAACAACGAC', 'GCCGGCCGCCCGCCCCCCCCCCCCCCCGGCCCCCCGCGCGGCACAACAAC', 'GCCGGCCCGCAGCCGCCAGCGCCCACCGGCGCCCCGGCGCCAACAACGAC', 'GCCGGCCCGCAGCCGCCACCGGCCACCGGCGCCCCGGCGCCAACAACGAC'],
'job745' : ['GCCGGCCGCCCGGCACCGCCGACGCCCGGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACCGCCCGCACCCGGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCTCCAGGCACAGCCCGCCCCCAGCCCCAGCGCCGGCAAATACGA', 'GCCGGCCGCCCGGCACCGCCCGCACCGCGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACCGCCAGCCCCGAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACAGCCCGCACCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACAGCCCGCGCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACAGCCAGCCCCGAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACCGCCAGCCCCGCGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACCGCCAGCCCCCGGCCCCGGCGCCGGCAACAACGA'],
'job782' : ['GCCGGCCGCTCGGCACAGCCCCCCCCCGCCCCCCTGCTGCCGACAACGAC', 'GCCGGCCGCCAGGCACAGCCAGCCCCCGCGGCCCCGCTGCCGACAACGAC', 'GCCGGCCGCCAGGCACAGCCAGCCCCCGCGGCCCCGCGGCCGACAACGAC', 'GCCGGCCGCCAGGCACAGCCACCCCCCGCGGCCCCGCTGCCGACAACGAC', 'GCCGGCCGCCAGGCCCAGCCAGCCCCCGCGGCCCCGCGGCCGACAACAAC', 'GCCGGCCGCCAGGCACAGCCAGCCCCCGCGCCCCTGCGGCCGACAACAAC', 'GCCGGCCGCCAGGCCCAGCGCGCCCCCGCGGCCCCGCGGCCGACAACAAC', 'GCCGGCCGCCAGGCACAGCCAGCCCCCGCCGCCCCGCGGCCGACAACAAC', 'GCCGGCCGCCAGGCACAGCGCGCCCCCGCGCCCCCGCGGCCGACAACAAC', 'GCCGGCCGCCAGGCACAGCCAGCCCCCGCGCCCCCGCGGCCGACAACAAC']
}

# job732 selNSGA3 cxTwoPoint 25個
# job762 21個
# job763 35個
# job772 5個
nsga3_two = {
'job732' : ['GCCGGCCCGCACGCCCCGGCCCCGAGCCCCCAGCGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACAGGCCCCGCCCGGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCCGCAGCCCGCAGCCGCGAGCCCCCAGCGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACAGGCCCCGCCCGCCCCCGGCGCCGGCACAACAAC', 'GCCGGCCCGCAGCCACCAGCCGCGAGCCCCCAGCGCGCCGGCACAACAAC', 'GCCGCGCCCCACGGCACAGCCGCGAGCCCCCCCGGGTGCGGCACAACACG', 'GCCGCGCCCCACGGCACAGCCGAGCCCGGCCCCAGGTGCGGCACAACACG', 'GCCGGCCCGCACCGCCCAGCCCCGAGCCCCCAGCGCGCCGGCACAACAAC', 'GCCGGGCCCCACGGCACAGCCGCCCCCGGCCCCGGGTCCGGCACAACACC', 'GCCGGCCGCCAGGCACAGGCCGCCACCGCCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACAGGCCGCCCCCGCCCCCGGCGCCGGCACAACAAC', 'GCCGCCCTCCAGGGCACAGCGGCGAGCGCACCCAGGTCCGGCACAACACG', 'GCCGGGCCCCACGGCACAGCCGCGAGCCCCAGCGCCGGCACGACAACACC', 'GCCGCCCTCCAGGGCACAGCGGCGAGCGCACCCAGGTGCGGCACAACACG', 'GCCGCGCCCCACGGCACAGCCGACCCCGGCCCCGGCTGCGGCACAACACG', 'GCCGGCCCGCAGCCCCCAGCCCCGAGCCCCCAGCGCGCCGGCACAACAAC', 'GCCGCGCCCCACGGCACAGCCGACCCCGGCCCCGGGTGCGGCACAACACG', 'GCCGGCCGCCAGGCACAGCCCCCGCCCGGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCCGCACGCCCCAGCCCCGAGCCCCCAGCGCGCCGGCACAACAAC', 'GCCGCGCCCCACGGCACAGCCGACCCCGGCCCCAGGTGCGGCACAACACG', 'GCCGCGCCCCACGGCACAGCCGCGAGCGCCCCCGGGTGCGGCACAACACC', 'GCCGCGCCCCACGGCACAGCCGCGAGCGCCCCCGGGTGCGGCACAACACG', 'GCCGGCCGCACCGGCACAGCCGCGAGCGCCACCGCGGCCGGCACAACACC', 'GCCGGCCCGCAGCCCGCAGCCCCGAGCCCCCAGCGCGCCGGCACAACAAC', 'GCCGCGCCCCACGGCACAGCCGACCCCGGCCCCAGCGGCGGCACAACACG'],
'job762' : ['GCCGCGCCGCACCGCACCGGCACCGGCGCAGCCCCGAGCGCGAACAACGA', 'GCCCCGCGCCACGGCACCGGCCCCGGCGCAGCCCCGAGCGCGCCAACAAC', 'GCTGGCGGCCCCCCGACGGCACAGCCCCCAGCCGGAGCCGGTCCATACGA', 'GCCCCGCGGCGCCGCACCGGCACCGGCGCAGCCCCGAGCGCGCCAACAAC', 'GCCCCGCGCCCCGGCACCCGCCCCGGCGCAGCCCCGAGCGCGCCAACAAC', 'GCCCCGCGGCCCCGCACCGGCACCGGCGCAGCCCCGAGCGCGCCAACAAC', 'GCCCCGCGGCCCGGCACCGGCCCCGGCGCAGCCCCGAGCGCGCCAACAAC', 'GCCGGCCGCCACCGCACCGGCACCGGCGCAGCCGCGACCGGCAACAACGA', 'CCCCGCGCGCCCCGGCCCCGCCCCGCGGCAGCCCCGAGCGCGCCAACAAC', 'GCCGCGCGCCACCGGCCCGGCACCGGCGCAGCCCCGAGCGCGAACAACGA', 'GCCGCCCGCCACCGGCCCGGCACCGGCGCAGCCCCGAGCGCGAACAACGA', 'CCCCCGCGCCGCGGCACCCGCCCCGGCGCAGCCCCGAGCGCGCCAACAAC', 'GCCGCGCCGCCCCGCACCGGCACCGGCGCAGCCCCGAGCGCGAACAACGA', 'GCCCCGCGCCCCGGCACCGGCCCCCGCGCAGCCCCGAGCGCGCCAACAAC', 'GCCCCGCGCCACGGCACCCGCCCCGGCGCAGCCCCGAGCGCGCCAACAAC', 'GCCGGCCGCCACCGGCACCGCACGGCCGCAGCCGGCGCCGGCAACAACGA', 'GCCGCGGGCCACCGGCCCGGCACCGGCGCAGCCCCGAGCGCGAACAACGA', 'GCCGCGCGGCCCCGCACCGGCACCGGCGCAGCCCCGAGCGCGAACAACGA', 'GCCCCGCGGCCCCGCACCGGCCCCGGCGCAGCCCCGAGCGCGCCAACAAC', 'GCCGCGCGGCACCGGCCCGGCACCGGCGCAGCCCCGAGCGCGAACAACGA', 'GCCGGCCGCCGCCGCACCGGCACCGGCGCAGCCGCGACCGGCAACAACGA'],
'job763' : ['GCCGGCCGCCAGGCACCCGCGAGCCCCCGGCCCGGCGCCGGCACAACAAC', 'GCCGGCCTCCAGGCACAGGCCGCCCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCTCCAGGCACAGGCCGCCCCCAGCCCCGGAGCCCACGAATACAA', 'GCCGGCCGCCAGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCAACAACAC', 'GCCGGCCGCCAGGCACAGCCCAGCCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCAGGCACAGCCCAGCCCCGGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACAGCCCAGCCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCAGGCACCGCCCGCCCCCAGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACAGCCCAGCCCCGGCCCCGGCGCCGGCAACAACAC', 'GCCGGCCGCCAGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCCGGCACCGCCCACCCCGCGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCAGGCACAGCCCGGCCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCAGGCACCCGCGAGCCCCGGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACCCGCGACCCCCAGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCCGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCGGCCAGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCAACAACAC', 'GCCGGCCGCCCGGCACAGCCGAGCCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCGGCCCGGCACAGGCCAGCCCCGGCCCCGGCGCCGGCAACAACAC', 'GCCGGCCGCCAGGCACCCGCGAGCCCCAGCCCCGGCGCCGGCACAACAAC', 'GCCGGCGGCCAGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCACATACGA', 'GCCGGCCGCCAGGCACAGCCCACCCCCAGCCCCGGCGCCGGCAAATACGA', 'GCCGGCCGCCCGGCACCGCCGACCCCCGGCCCCGGCGCCGGCAACAACAA', 'GCCGGCCGCCCGGCACCGCCGACCCCGCGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCAGGCACAGCCCGCCCCGCGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACAGCCCAGCCCCAGCCCCGGCGCCGGCAAATACGA', 'GCCGGCCGCCCGGCACAGCCGAGCCCCGGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACCCGCCACCCCCAGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACCCGCCGCCCCCAGCCCCGGCGCCGGCACAACAAC', 'GCCGGCCGCCAGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCAAATACGA', 'GCCGGCCGCCAGGCACAGCCCGGCCCCAGCCCCGGCGCCGGCAACAACAC', 'GCCGGCCGCCAGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCAGGCACAGCCCAGCCCCGGCCCCGGCGCCGGCAAATACGA', 'GCCGGCCGCCAGGCACAGCCCGCCCCCAGCCCCGGCGCCGGCAAATACAC', 'GCCGGCCGCCCGGCACCGCCGACCCCCGGCCCCGGCGCCGGCAACAACGA', 'GCCGGCCGCCCGGCACCGCCGAGCCCCGGCCCCGGCGCCGGCACAACAAC'],
'job772' : ['CCGCGCCCCCGCGGCCCACCGCCCCCGCGCGCCGAACCGCGCCAACAACA', 'TCCGCCCGCCACCGGCCACAGCCGGCCACCCTGGCAGCAGGCGACCCATA', 'CCGCGCCCCCGCGGCCCACCGCCCCCGCGCGCCGCACCGCGCCAACAACA', 'CCGGCCCGCCACCGGCCACAGCCGGCCACCCTGGCAGCAGGCGAACAACA', 'CCGCGCCCCCGCGGCCCACCGCCCCCGCGCGCCGACCCGCGCCAACAACA']
}

# job741 selNSGA2 cxUniform 33個
# job751 600Gen 31個
# job753 1000Gen 33個
# job774 33個
nsga2_unif = {
'job741' : ['GCCGGCCGGCCGGCACAGCCCCCAGCCGCCCCCCTGCAGCCGACAACGAC', 'GCCCGCCGCCCCCCGCCCCCCCCCCCCGCCCACCCGCGCGGCACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCGAACAACGAC', 'GCCGGCCGCCCGGCACAGCCCCCCGCCGGGCCCCGCCGGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCCGACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCCCCCCTGCAGCCGACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCGCCCCTGCCGGCAACAACGAC', 'GCCGGCCGCCCGGCACAGCCCCCCGCCGGGCCCGCCCGGCCAACAACGAC', 'GCCGGCCGCTAGGCACAGCCCCCAGCCGCCCCCCTGCAGCCAACAACGAC', 'GCCCGCCGCCCGCCGCCCCCCCCCCCCGCCCACCCGCGCGGCACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCCCCCCTGCAGCGAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCCCCCCTGCCGGCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCACCCGCGCCCCTGCGGCCGACAACAAC', 'GCCGGCCGCCCCGCACCGCCCACCGCCGCCCCCCGGCCGGCAACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCGAACAACGAC', 'GCCGGCCGCTGCGCACAGCCCACCCCCGCGCCCCGGCCGGCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCACTCCCGCGCCCCGGCCGGCAACAACGAC', 'GCCGGCCGCCCCGCACCGCCCCCAGCCGCCCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCTCCCGCGCCCCTGCGGCCGACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGCCCCGCACCGCCCACCGCCGCGCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCCCGGCACAGCCCCCGCCCGGGCCCCGGCGCCGAGCAACAAC', 'GCCGGCCGCCAGGCACAGCCCACCCCCGCGCCCCGGCGGCCGACAACAAC', 'GCCGGCCGCCAGGCACAGCCCGCCCCCGGCGCCCAGCGGCCGACAACAAC', 'GCCGGCCGCCAGGCACAGGCCGCCCCCGGCGCCCAGCGGCCGACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCGAACAACGAC', 'GCCGGCCGCCGCGCACAGCCCACCCCCGCGCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACAAC'],
'job751' : ['GCCGGCCGCTCGGCACAGCCCCCACCCGCGCCCCTGCGGCCGACAACAAC', 'GCCGGCCGCCCGGCACAGCCCCCGCCCGGGCCCCGGCGCCGAGCAACAAC', 'GCCGGCCGCCCCGCACCGCCCACCGCCGCCCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCCAGGCACAGCCCACCCCCGCGCCCCGGCGGCCGACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCCAACAACGAC', 'GCCGGCCGCCCCGCACCGCCCACCGCCGCGCCCCGGCCGGCAACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCGCCCCTGCCGGCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCTCCCGCGCCCCTGCGGCCGACAACAAC', 'GCCCGCCGCCCGCCGCCCCCCCCCCCCGCCCCCCCGCGCGGCACAACAAC', 'GCCGGCCGGCCGGCACAGCCCACTCCCGCGCCCCGGCCGGCAACAACGAC', 'GCCGGCCGCCCGGCACAGCCCCCCGCCGGGCCCGCCCGGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCCCCCCTGCCGGCAACAACGAC', 'GCCGGCCGCCAGGCACAGGCCGCCCCCGGCGCCCAGCGGCCGACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCCCCCCTGCAGCCGACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACAAC', 'GCCGGCCGCTAGGCACAGCCCCCAGCCGCCCCCCTGCAGCCAACAACGAC', 'GCCCGCCGCCCCCCGCCCCCCCCCCCCGCCCACCCGCGCGGCACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCCCCCCTGCAGCGAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGCCCGGCACAGCCCCCCGCCGGGCCCCGCCGGCCAACAACGAC', 'GCCGGCCGCCAGGCACAGCCCGCAGCCGCGCCCCTGCGGCCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCGAACAACGAC', 'GCCGGCCGCCGCGCACAGCCCACCCCCGCGCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCTGCGCACAGCCCACCCCCGCGCCCCGGCCGGCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCGAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCCCCCCTGCAGCCGACAACGAC', 'GCCGGCCGCCAGGCACAGCCCGCCCCCGGCGCCCAGCGGCCGACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACAAC'],
'job753' : ['GCCGGCCGCCCGGCACAGCCCCCCGCCGGGCCCCGCCGGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCCAACAACGAC', 'GCCGGCCGCCCGGCACAGCCCCCCGCCGGGCCCGCCCGGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACAAC', 'GCCGGCCGCCCCGCACCGCCCCCAGCCGCCCCCCGGCCGGCAACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCGCCCCTGCCGGCAACAACGAC', 'GCCGGCCGCCAGGCACAGCCCGCCCCCGGCGCCCAGCGGCCGACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCCGACAACGAC', 'GCCCGCCGCCCCCCGCCCCCCCCCCCCGCCCACCCGCGCGGCACAACAAC', 'GCCGGCCGCCCGGCACAGCCCCCGCCCGGGCCCCGGCGCCGAGCAACAAC', 'GCCGGCCGCCGCGCACAGCCCACCCCCGCGCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCTAGGCACAGCCCCCAGCCGCCCCCCTGCAGCCAACAACGAC', 'GCCCGCCGCCCGCCGCCCCCCCCCCCCGCCCACCCGCGCGGCACAACAAC', 'GCCGGCCGCCCCGCACCGCCCACCGCCGCCCCCCGGCCGGCAACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCGAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCACCCGCGCCCCTGCGGCCGACAACAAC', 'GCCGGCCGCCCCGCACCGCCCACCGCCGCGCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCTCCCGCGCCCCTGCGGCCGACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCCCCCCTGCCGGCAACAACGAC', 'GCCGGCCGCTGCGCACAGCCCACCCCCGCGCCCCGGCCGGCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCCCCCCTGCAGCGAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGCCAGGCACAGGCCGCCCCCGGCGCCCAGCGGCCGACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCCCCCCTGCAGCCGACAACGAC', 'GCCGGCCGGCCGGCACAGCCCACTCCCGCGCCCCGGCCGGCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCCCCCCTGCAGCCGACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCGAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCGAACAACGAC', 'GCCGGCCGCCAGGCACAGCCCACCCCCGCGCCCCGGCGGCCGACAACAAC'],
'job774' : ['GCCGGCCGCCCCGCACCGCCCACCGCCGCGCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCCCCCCTGCAGCGAACAACGAC', 'GCCCGCCGCCCCCCGCCCCCCCCCCCCGCCCACCCGCGCGGCACAACAAC', 'GCCGGCCGCCAGGCACAGGCCGCCCCCGGCGCCCAGCGGCCGACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACAAC', 'GCCGGCCGCCCGGCACAGCCCCCCGCCGGGCCCCGCCGGCCAACAACGAC', 'GCCGGCCGCCCCGCACCGCCCACCGCCGCCCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCTCCCGCGCCCCTGCGGCCGACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCGAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCACTCCCGCGCCCCGGCCGGCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCACCCGCGCCCCTGCGGCCGACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCCCCCCTGCAGCCGACAACGAC', 'GCCGGCCGCCCGGCACAGCCCCCCGCCGGGCCCGCCCGGCCAACAACGAC', 'GCCGGCCGCTGCGCACAGCCCACCCCCGCGCCCCGGCCGGCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCGCCCCTGCCGGCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCGAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCCCCCCTGCCGGCAACAACGAC', 'GCCGGCCGCTAGGCACAGCCCCCAGCCGCCCCCCTGCAGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCCGCCGACAACGAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCCCCCCTGCAGCCGACAACGAC', 'GCCGGCCGCCAGGCACAGCCCGCCCCCGGCGCCCAGCGGCCGACAACAAC', 'GCCGGCCGCCAGGCACAGCCCACCCCCGCGCCCCGGCGGCCGACAACAAC', 'GCCCGCCGCCCGCCGCCCCCCCCCCCCGCCCACCCGCGCGGCACAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCTCCCGCGCCCCTGCAGCCAACAACGAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCGAACAACGAC', 'GCCGGCCGCCCGGCACAGCCCCCGCCCGGGCCCCGGCGCCGAGCAACAAC', 'GCCGGCCGGCCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACGAC', 'GCCGGCCGCCGCGCACAGCCCACCCCCGCGCCCCGGCCGGCAACAACAAC', 'GCCGGCCGCTCGGCACAGCCCCCAGCCGCGCCCCTGCAGCCGACAACAAC', 'GCCGGCCGCCCCGCACCGCCCCCAGCCGCCCCCCGGCCGGCAACAACAAC']
}

# job742 selNSGA2 cxTwoPoint 39個
# job760 39個
# job761 39個
# job773 39個
nsga2_two = {
'job742' : ['GCCCGCCGCACCGGCACCGGCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGCCGCCCCGGCACAGCCGCGGCCGCAGCCCCGGGTCGAGCCACAAC', 'GCCCGCCGCACCGGCACAGCCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGGCCGCAGCCCCGCCGCAACAATACGA', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCGCGCGGCGAGCCACAAC', 'GCCGGGCCCCACGGCACAGCCGCGCCCGCTCCCCCCGGCCGAGCGACAAC', 'GCCGGGCCCCACGGCACAGCCCCGGCCGCAGCCGCGCCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCGAGCGACAAC', 'GCCGGGCCCACAGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCCCGCGCCCCGGCACCGCCCCGGCCGCAGCCCCGGCGCGAGCCACAAC', 'GCCGGGCCCCACGGCACAGCCGCGCCCCCGGCCCCGCCGCGAGCCACAAC', 'GCCGGGCCCCACGGCACAGCCGCGCCCCCAGCCGCGCCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCCCCGCCGCGAGCCACAAC', 'GCCCGCCGCCCCGGCACCGGCCCCAGCGCAGCCGCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCCGCGACAACACCA', 'GCCCCGCGCCCCGGCACCGGCCCGAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCCGCCGCCCCGGCACCGGCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCGGGCCCACAGGCACAGCCGCGCCCGCAGCCCAGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCCCAACAACACGA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCCACAACACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCGCGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCACCAACAACACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCCGAGCCGCGACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCAACAACACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACACAACGA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCGACAACACCA', 'GCCCGCCGCACCGGCACCGGCCCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCCGCCGCACCGGCACAGCCGCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACCGCCCCGGCCGCAGCCGCGCCGCAACAACACCA', 'GCCGGGCCCCACGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACAACACGA', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCCCGCGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCGACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCCCGCCGCGAGCCACAAC'],
'job760' : ['GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACAACACGA', 'GCCCCGCGCCCCGGCACCGCCCCGGCCGCAGCCCCGGCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCCCCGCCGCGAGCCACAAC', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCCACAACACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCCGAGCCGCGACAACACCA', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACACAACGA', 'GCCGGGCCCCCAGGCACAGCCGCGGCCGCAGCCCCGCCGCAACAATACGA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCAACAACACGA', 'GCCGGGCCCCACGGCACAGCCCCGGCCGCAGCCGCGCCGCAACAATACGA', 'GCCGGGCCCCACGGCACAGCCGCGCCCCCGGCCCCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCCCAACAACACGA', 'GCCGGGCCCCACGGCACAGCCGCGCCCCCAGCCGCGCCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCACAGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCGACAACACCA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCGACAACACCA', 'GCCGGGCCCACAGGCACAGCCGCGCCCGCAGCCCAGGCGCAACAATACGA', 'GCCGGCCGCCCCGGCACAGCCGCGGCCGCAGCCCCGGGTCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCGAGCGACAAC', 'GCCCGCCGCACCGGCACAGCCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCCGCCGCCCCGGCACCGGCCCCAGCGCAGCCGCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCCGCAACAACACCA', 'GCCGGGCCCCACGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCGCGGCGCAACAATACGA', 'GCCCGCCGCACCGGCACCGGCCCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCCCGCGCGGAGCACCAAC', 'GCCCGCCGCACCGGCACCGGCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCGGGCCCCACGGCACAGCCGCGCCCGCTCCCCCCGGCCGAGCGACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCACCAACAACACGA', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCGCGCGGCGAGCCACAAC', 'GCCCGCCGCCCCGGCACCGGCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCCGCCGCACCGGCACAGCCGCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCCGCGACAACACCA', 'GCCGGGCCCCCAGGCACCGCCCCGGCCGCAGCCGCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCCCGCCGCGAGCCACAAC', 'GCCCCGCGCCCCGGCACCGGCCCGAGCGCAGCCCCGAGCGGAGCACCAAC'],
'job761' : ['GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCGAGCGACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACAACACCA', 'GCCGGGCCCCACGGCACAGCCCCGGCCGCAGCCGCGCCGCAACAATACGA', 'GCCGGGCCCCCAGGCACCGCCCCGGCCGCAGCCGCGCCGCAACAACACCA', 'GCCGGGCCCACAGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCCCGCGCCCCGGCACCGCCCCGGCCGCAGCCCCGGCGCGAGCCACAAC', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCGCGCGGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCGCGGCGCAACAATACGA', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCCGCCGCACCGGCACCGGCCCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCACGGCACAGCCGCGCCCCCGGCCCCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACAACACGA', 'GCCCCGCGCCCCGGCACCGGCCCGAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACACAACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCACCAACAACACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCCGCGACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGGCCGCAGCCCCGCCGCAACAATACGA', 'GCCCGCCGCACCGGCACAGCCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCCGCCGCCCCGGCACCGGCCCCAGCGCAGCCGCGCCGCGAGCCACAAC', 'GCCGGGCCCCACGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCGACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCCGCAACAACACCA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCCGAGCCGCGACAACACCA', 'GCCGGCCGCCCCGGCACAGCCGCGGCCGCAGCCCCGGGTCGAGCCACAAC', 'GCCGGGCCCCACGGCACAGCCGCGCCCCCAGCCGCGCCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCAACAACACGA', 'GCCCGCCGCCCCGGCACCGGCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCCCGCGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCGACAACACCA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCCACAACACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCCCGCCGCGAGCCACAAC', 'GCCCGCCGCACCGGCACAGCCGCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCACAGGCACAGCCGCGCCCGCAGCCCAGGCGCAACAATACGA', 'GCCCGCCGCACCGGCACCGGCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCCCCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCCCAACAACACGA', 'GCCGGGCCCCACGGCACAGCCGCGCCCGCTCCCCCCGGCCGAGCGACAAC'],
'job773' : ['GCCGGGCCCCACGGCACAGCCGCGCCCGCTCCCCCCGGCCGAGCGACAAC', 'GCCCGCCGCCCCGGCACCGGCCCCAGCGCAGCCGCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCCCCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCCCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCACCAACAACACGA', 'GCCGGGCCCCCAGGCACAGCCGCGGCCGCAGCCCCGCCGCAACAATACGA', 'GCCCGCCGCACCGGCACCGGCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCGGGCCCACAGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACAACACGA', 'GCCGGGCCCACAGGCACAGCCGCGCCCGCAGCCCAGGCGCAACAATACGA', 'GCCGGGCCCCACGGCACAGCCGCGCCCCCGGCCCCGCCGCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCAACAACACGA', 'GCCCCGCGCCCCGGCACCGCCCCGGCCGCAGCCCCGGCGCGAGCCACAAC', 'GCCCGCCGCACCGGCACAGCCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCGCGCGGCGAGCCACAAC', 'GCCGGGCCCCACGGCACAGCCGCGCCCCCAGCCGCGCCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCCCAACAACACGA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCGACAACACCA', 'GCCCGCCGCCCCGGCACCGGCCCCAGCGCAGCCCCGCGGCGAGCCACAAC', 'GCCGGGCCCCACGGCACAGCCCCGGCCGCAGCCGCGCCGCAACAATACGA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCCGAGCCGCGACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCGCGGCGCAACAATACGA', 'GCCGGCCGCCCCGGCACAGCCGCGGCCGCAGCCCCGGGTCGAGCCACAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCGAGCGACAAC', 'GCCCGCCGCACCGGCACAGCCGCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCGCCGACAACACCA', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCCCGCGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACAACACCA', 'GCCGGGCCCCCAGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCCCGCGCCCCGGCACCGGCCCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCAGCGCCGCCGCAACACAACGA', 'GCCCCGCGCCCCGGCACCGGCCCGAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCCAGGCACAGCCGCGCCCCCGGCGCCGCCGCGACAACACCA', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCAACAACACCA', 'GCCCGCCGCACCGGCACCGGCCCCAGCGCAGCCCCGAGCGGAGCACCAAC', 'GCCGGGCCCCACGGCACCGCCCCGGCCGCAGCCGCGCCGCCACAACACGA', 'GCCGGGCCCCACGGCACAGCCGCGCCCGCAGCCCCGGCGCAACAATACGA', 'GCCGGGCCCCCAGGCACCGCCCCGGCCGCAGCCGCGCCGCAACAACACCA']
}

nsga3_unifs = []
nsga3_twos = []
nsga2_unifs = []
nsga2_twos = []
for seqs in nsga3_unif.values():
    nsga3_unifs.extend(seqs)
for seqs in nsga3_two.values():
    nsga3_twos.extend(seqs)
for seqs in nsga2_unif.values():
    nsga2_unifs.extend(seqs)
for seqs in nsga2_two.values():
    nsga2_twos.extend(seqs)

# https://www.ncbi.nlm.nih.gov/nuccore/OK120841.1
mRNA1237 = 'ATGTTCGTGTTCCTGGTGCTGCTGCCCCTGGTGAGCAGCCAGTGCGTGAACCTGACCACCCGGACCCAGCTGCCACCAGCCTACACCAACAGCTTCACCCGGGGCGTCTACTACCCCGACAAGGTGTTCCGGAGCAGCGTCCTGCACAGCACCCAGGACCTGTTCCTGCCCTTCTTCAGCAACGTGACCTGGTTCCACGCCATCCACGTGAGCGGCACCAACGGCACCAAGCGGTTCGACAACCCCGTGCTGCCCTTCAACGACGGCGTGTACTTCGCCAGCACCGAGAAGAGCAACATCATCCGGGGCTGGATCTTCGGCACCACCCTGGACAGCAAGACCCAGAGCCTGCTGATCGTGAATAACGCCACCAACGTGGTGATCAAGGTGTGCGAGTTCCAGTTCTGCAACGACCCCTTCCTGGGCGTGTACTACCACAAGAACAACAAGAGCTGGATGGAGAGCGAGTTCCGGGTGTACAGCAGCGCCAACAACTGCACCTTCGAGTACGTGAGCCAGCCCTTCCTGATGGACCTGGAGGGCAAGCAGGGCAACTTCAAGAACCTGCGGGAGTTCGTGTTCAAGAACATCGACGGCTACTTCAAGATCTACAGCAAGCACACCCCAATCAACCTGGTGCGGGATCTGCCCCAGGGCTTCTCAGCCCTGGAGCCCCTGGTGGACCTGCCCATCGGCATCAACATCACCCGGTTCCAGACCCTGCTGGCCCTGCACCGGAGCTACCTGACCCCAGGCGACAGCAGCAGCGGGTGGACAGCAGGCGCGGCTGCTTACTACGTGGGCTACCTGCAGCCCCGGACCTTCCTGCTGAAGTACAACGAGAACGGCACCATCACCGACGCCGTGGACTGCGCCCTGGACCCTCTGAGCGAGACCAAGTGCACCCTGAAGAGCTTCACCGTGGAGAAGGGCATCTACCAGACCAGCAACTTCCGGGTGCAGCCCACCGAGAGCATCGTGCGGTTCCCCAACATCACCAACCTGTGCCCCTTCGGCGAGGTGTTCAACGCCACCCGGTTCGCCAGCGTGTACGCCTGGAACCGGAAGCGGATCAGCAACTGCGTGGCCGACTACAGCGTGCTGTACAACAGCGCCAGCTTCAGCACCTTCAAGTGCTACGGCGTGAGCCCCACCAAGCTGAACGACCTGTGCTTCACCAACGTGTACGCCGACAGCTTCGTGATCCGTGGCGACGAGGTGCGGCAGATCGCACCCGGCCAGACAGGCAAGATCGCCGACTACAACTACAAGCTGCCCGACGACTTCACCGGCTGCGTGATCGCCTGGAACAGCAACAACCTCGACAGCAAGGTGGGCGGCAACTACAACTACCTGTACCGGCTGTTCCGGAAGAGCAACCTGAAGCCCTTCGAGCGGGACATCAGCACCGAGATCTACCAAGCCGGCTCCACCCCTTGCAACGGCGTGGAGGGCTTCAACTGCTACTTCCCTCTGCAGAGCTACGGCTTCCAGCCCACCAACGGCGTGGGCTACCAGCCCTACCGGGTGGTGGTGCTGAGCTTCGAGCTGCTGCACGCCCCAGCCACCGTGTGTGGCCCCAAGAAGAGCACCAACCTGGTGAAGAACAAGTGCGTGAACTTCAACTTCAACGGCCTTACCGGCACCGGCGTGCTGACCGAGAGCAACAAGAAATTCCTGCCCTTTCAGCAGTTCGGCCGGGACATCGCCGACACCACCGACGCTGTGCGGGATCCCCAGACCCTGGAGATCCTGGACATCACCCCTTGCAGCTTCGGCGGCGTGAGCGTGATCACCCCAGGCACCAACACCAGCAACCAGGTGGCCGTGCTGTACCAGGACGTGAACTGCACCGAGGTGCCCGTGGCCATCCACGCCGACCAGCTGACACCCACCTGGCGGGTCTACAGCACCGGCAGCAACGTGTTCCAGACCCGGGCCGGTTGCCTGATCGGCGCCGAGCACGTGAACAACAGCTACGAGTGCGACATCCCCATCGGCGCCGGCATCTGTGCCAGCTACCAGACCCAGACCAATTCACCCCGGAGGGCAAGGAGCGTGGCCAGCCAGAGCATCATCGCCTACACCATGAGCCTGGGCGCCGAGAACAGCGTGGCCTACAGCAACAACAGCATCGCCATCCCCACCAACTTCACCATCAGCGTGACCACCGAGATTCTGCCCGTGAGCATGACCAAGACCAGCGTGGACTGCACCATGTACATCTGCGGCGACAGCACCGAGTGCAGCAACCTGCTGCTGCAGTACGGCAGCTTCTGCACCCAGCTGAACCGGGCCCTGACCGGCATCGCCGTGGAGCAGGACAAGAACACCCAGGAGGTGTTCGCCCAGGTGAAGCAGATCTACAAGACCCCTCCCATCAAGGACTTCGGCGGCTTCAACTTCAGCCAGATCCTGCCCGACCCCAGCAAGCCCAGCAAGCGGAGCTTCATCGAGGACCTGCTGTTCAACAAGGTGACCCTAGCCGACGCCGGCTTCATCAAGCAGTACGGCGACTGCCTCGGCGACATAGCCGCCCGGGACCTGATCTGCGCCCAGAAGTTCAACGGCCTGACCGTGCTGCCTCCCCTGCTGACCGACGAGATGATCGCCCAGTACACCAGCGCCCTGTTAGCCGGAACCATCACCAGCGGCTGGACTTTCGGCGCTGGAGCCGCTCTGCAGATCCCCTTCGCCATGCAGATGGCCTACCGGTTCAACGGCATCGGCGTGACCCAGAACGTGCTGTACGAGAACCAGAAGCTGATCGCCAACCAGTTCAACAGCGCCATCGGCAAGATCCAGGACAGCCTGAGCAGCACCGCTAGCGCCCTGGGCAAGCTGCAGGACGTGGTGAACCAGAACGCCCAGGCCCTGAACACCCTGGTGAAGCAGCTGAGCAGCAACTTCGGCGCCATCAGCAGCGTGCTGAACGACATCCTGAGCCGGCTGGACCCTCCCGAGGCCGAGGTGCAGATCGACCGGCTGATCACTGGCCGGCTGCAGAGCCTGCAGACCTACGTGACCCAGCAGCTGATCCGGGCCGCCGAGATTCGGGCCAGCGCCAACCTGGCCGCCACCAAGATGAGCGAGTGCGTGCTGGGCCAGAGCAAGCGGGTGGACTTCTGCGGCAAGGGCTACCACCTGATGAGCTTTCCCCAGAGCGCACCCCACGGAGTGGTGTTCCTGCACGTGACCTACGTGCCCGCCCAGGAGAAGAACTTCACCACCGCCCCAGCCATCTGCCACGACGGCAAGGCCCACTTTCCCCGGGAGGGCGTGTTCGTGAGCAACGGCACCCACTGGTTCGTGACCCAGCGGAACTTCTACGAGCCCCAGATCATCACCACCGACAACACCTTCGTGAGCGGCAACTGCGACGTGGTGATCGGCATCGTGAACAACACCGTGTACGATCCCCTGCAGCCCGAGCTGGACAGCTTCAAGGAGGAGCTGGACAAGTACTTCAAGAATCACACCAGCCCCGACGTGGACCTGGGCGACATCAGCGGCATCAACGCCAGCGTGGTGAACATCCAGAAGGAGATCGATCGGCTGAACGAGGTGGCCAAGAACCTGAACGAGAGCCTGATCGACCTGCAGGAGCTGGGCAAGTACGAGCAGTACATCAAGTGGCCCTGGTACATCTGGCTGGGCTTCATCGCCGGCCTGATCGCCATCGTGATGGTGACCATCATGCTGTGCTGCATGACCAGCTGCTGCAGCTGCCTGAAGGGCTGTTGCAGCTGCGGCAGCTGCTGCAAGTTCGACGAGGACGACAGCGAGCCCGTGCTGAAGGGCGTGAAGCTGCACTACACCTGATAATAG'
mRNA1237s = []
for i in range(0, len(mRNA1237), 50):
    mRNA1237s.append(mRNA1237[i:i+50])

mRNA1237s.pop() # 50bp未満の最後の要素を削除
# for t in mRNA1237s:
#     print(t)

def pred(seq):
    m1 = TE_predictor.predictor()
    m2 = Deg_predictor.predictor()
    print(m1.predict(seq))
    print(Deg_predictor.score_sum(m2.predict(seq), label='deg_50C'))

def GC_visualize(seqs):
    m1 = TE_predictor.predictor()
    m2 = Deg_predictor.predictor()
    TEs = []
    Degs = []
    GCs = []
    for seq in seqs:
        GC = 0
        for i in range(0, len(seq)):
            if seq[i] == 'G' or seq[i] == 'C':
                GC += 1
        gc_percent = GC / len(seq)

        TEs.append(m1.predict(seq))
        Degs.append(Deg_predictor.score_sum(m2.predict(seq), label='deg_50C'))
        GCs.append(gc_percent)

    import matplotlib.cm as cm
    sc = plt.scatter(TEs, Degs, c=GCs, cmap=cm.coolwarm)
    plt.colorbar(sc).set_label('GC content')
    plt.xlabel('TE')
    plt.ylabel('Deg')
    plt.savefig('../slurm/logs/statics/img/GC_visualize.png')


def vs_target(samples, labels=None, title=None):
    import seaborn as sns
    import matplotlib.pyplot as plt
    import pandas as pd
    import numpy as np

    n = len(samples)
    data = []

    m1 = TE_predictor.predictor()
    m2 = Deg_predictor.predictor()

    if labels is None:
        labels = ['NSGA3+cxUniform', 'NSGA3+cxTwoPoint', 'NSGA2+cxUniform', 'NSGA2+cxTwoPoint']

    for i, (seqs, label) in enumerate(zip(samples, labels)):
        for seq in seqs:
            te = m1.predict(seq)
            deg = Deg_predictor.score_sum(m2.predict(seq), label='deg_50C')
            data.append((te, deg, label))

    # DataFrameに変換
    df = pd.DataFrame(data, columns=['TE', 'Deg', 'Algorithm'])

    # 最も右下の点を特定
    df['diff'] = df['Deg'] - df['TE']
    rightmost_lowest_point = df.loc[df['diff'].idxmin()]

    # Seabornでプロット
    plt.figure(figsize=(8, 6))
    sns.scatterplot(data=df, x='TE', y='Deg', hue='Algorithm', palette='bright', alpha=0.7, s=20)

    # y = x の線を描画
    x = np.linspace(-0.8, 2.8, 100)
    y = np.linspace(3.8, 19.0, 100)
    X, Y = np.meshgrid(x, y)
    Z = X - Y  # 斜線のパターン

    plt.contour(X, Y, Z, levels=np.arange(-10, 10, 2), colors="gray", linestyles="--", alpha=0.5)
    plt.plot(X[0], X[0], color="gray", label="y = x", linestyle="--", alpha=0.5)


    # 最も右下の点を強調
    import matplotlib.patches as patches
    circle = patches.Ellipse((rightmost_lowest_point['TE'], rightmost_lowest_point['Deg']), width=0.08, height=0.3, color='red', fill=False, linewidth=2)
    plt.gca().add_patch(circle)
    
    # 軸設定
    plt.xlabel('TE')
    plt.ylabel('Deg')
    plt.xlim(-0.8, 2.8)
    plt.ylim(3.8, 19.0)
    plt.legend()

    if title is None:
        plt.savefig('../slurm/logs/statics/img/all_visualize.png')
    else:
        plt.savefig('../slurm/logs/statics/img/'+ title + '.png')

def check_divercity(seqs):
    st = set()
    for seq in seqs:
        st.add(seq)
    print(len(st))

if __name__ == '__main__':
    # GC_visualize(job728)
    # pred(mRNA1237)
    # vs_target(nsga3_unif.values(), labels = ['seq1', 'seq2', 'seq3', 'seq4'], title='nsga3_unif')
    # vs_target(nsga3_two.values(), labels = ['seq1', 'seq2', 'seq3', 'seq4'], title='nsga3_two')
    # vs_target(nsga2_unif.values(), labels = ['seq1', 'seq2', 'seq3', 'seq4'], title='nsga2_unif')
    # vs_target(nsga2_two.values(), labels = ['seq1', 'seq2', 'seq3', 'seq4'], title='nsga2_two')

    # vs_target([nsga3_unifs, nsga3_twos, nsga2_unifs, nsga2_twos], labels=['NSGA3+Uniform', 'NSGA3+TwoPoint', 'NSGA2+Uniform', 'NSGA2+TwoPoint'], title='all')

    check_divercity(nsga3_unifs)
    check_divercity(nsga3_twos)
    check_divercity(nsga2_unifs)
    check_divercity(nsga2_twos)